In [1]:
#Numpy(Numerical Python)
#to import any package use "import keyword"
import numpy as np

In [2]:
#To know the version of NumPy
np.__version__

'2.1.3'

In [3]:
my_list = [0, 1, 2, 3, 4, 5]

In [4]:
print(my_list)

[0, 1, 2, 3, 4, 5]


In [5]:
type(my_list)

list

In [6]:
#To Convert list into array 
arr = np.array(my_list)

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


<b>arange()</b><br>
Syntax:<br>
<b>numpy.arange(start, stop, step, dtype = None)</b>

In [8]:
#arange() - used to create the sequence of numbers - kind of like range(), but more powerful because it works with floats too. 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<b>range() Vs arange()</b> <br>
range() - works only with integers.<br>
np.arange() - works with integers and floats.<br>

In [9]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(10,20,5)

array([10, 15])

In [11]:
np.arange(20,10) #Note: The first argument must be less then second argument

array([], dtype=int64)

In [12]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

<b>zero() -</b> In Python zero() function is used to create an array filled entirely with zero(0).<br>
<b>Syntax:</b><br>
numpy.zeros(shape, dtype = float)

In [13]:
#zero()
np.zeros(5)#Parameter Tunning

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5, dtype = int) #Hyper Parameter Tunning

array([0, 0, 0, 0, 0])

In [15]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [16]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros([5,5] , dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

<b>ones() -</b> In Python ones() function is used to create an array filled entirely with one(1).<br>
<b>Syntax:</b><br>
numpy.ones(shape, dtype = float)

In [18]:
#ones()
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [20]:
np.ones([4, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<b>random:<b>random is actually a modlue (numpy.random) that contains many functions to fenerate random numbers and perform random operations on arrays.


In [21]:
#rand() - is a function in numpy.random module that generates random floating - point numbers uniformly between 0(inclusive) and 1(exclusive).
np.random.rand() #single random float  

0.414094534183698

In [23]:
np.random.rand(3) #1D array of random float   

array([0.91667623, 0.41284235, 0.32864013])

In [39]:
np.random.rand(3, 2) #2D array of random float  

array([[0.19792887, 0.76358727],
       [0.88527661, 0.92055419],
       [0.03430966, 0.51823491]])

In [24]:
np.random.randint(4, 6)

4

In [25]:
np.random.randint(0, 10)

4

In [26]:
np.random.randint(0, 10, 4)

array([8, 4, 7, 6], dtype=int32)

In [27]:
np.random.randint(0, 10, 5)

array([4, 2, 3, 1, 2], dtype=int32)

In [40]:
n = np.random.randint(10, 40, (8, 10))# randint(start, ending, (rows, columns))
print(n)

[[31 13 22 37 22 39 17 14 13 28]
 [21 36 23 33 28 38 38 38 28 13]
 [13 34 32 14 13 36 27 23 18 34]
 [33 18 28 39 15 17 31 35 14 19]
 [35 24 15 30 15 32 16 31 22 37]
 [32 29 20 32 14 19 14 33 19 18]
 [31 37 22 29 10 23 15 36 27 27]
 [10 33 16 21 28 10 15 38 29 14]]


In [41]:
#Accessing the elemnts of array using index.
n[5]

array([32, 29, 20, 32, 14, 19, 14, 33, 19, 18], dtype=int32)

In [30]:
#Accessing elements of array using slicing.
n[0:6]

array([[39, 15, 15, 36, 27, 26, 39, 19, 31, 39],
       [18, 25, 25, 12, 23, 14, 31, 28, 19, 18],
       [11, 21, 24, 17, 39, 33, 18, 22, 11, 12],
       [34, 16, 36, 33, 24, 14, 13, 37, 23, 18],
       [23, 12, 21, 33, 32, 36, 21, 30, 12, 22],
       [22, 25, 22, 11, 28, 25, 12, 18, 10, 13]], dtype=int32)

In [31]:
n[::-1] #reverse

array([[25, 25, 10, 38, 18, 28, 21, 13, 38, 33],
       [36, 27, 26, 31, 21, 18, 30, 39, 28, 33],
       [22, 25, 22, 11, 28, 25, 12, 18, 10, 13],
       [23, 12, 21, 33, 32, 36, 21, 30, 12, 22],
       [34, 16, 36, 33, 24, 14, 13, 37, 23, 18],
       [11, 21, 24, 17, 39, 33, 18, 22, 11, 12],
       [18, 25, 25, 12, 23, 14, 31, 28, 19, 18],
       [39, 15, 15, 36, 27, 26, 39, 19, 31, 39]], dtype=int32)

In [32]:
n[::-3]

array([[25, 25, 10, 38, 18, 28, 21, 13, 38, 33],
       [23, 12, 21, 33, 32, 36, 21, 30, 12, 22],
       [18, 25, 25, 12, 23, 14, 31, 28, 19, 18]], dtype=int32)

In [33]:
n[0:5]

array([[39, 15, 15, 36, 27, 26, 39, 19, 31, 39],
       [18, 25, 25, 12, 23, 14, 31, 28, 19, 18],
       [11, 21, 24, 17, 39, 33, 18, 22, 11, 12],
       [34, 16, 36, 33, 24, 14, 13, 37, 23, 18],
       [23, 12, 21, 33, 32, 36, 21, 30, 12, 22]], dtype=int32)

In [34]:
print(n[0,5])

26


In [35]:
print(n[5, -3])

18


In [36]:
np.arange(1,13).reshape(3, 4) #reshape() - To change the structure of numbers.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
np.arange(1,13).reshape(6,2 )

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [38]:
np.arange(1,13).reshape(5, 5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [44]:
x=np.int32(10)
print(x)

10
